# Template only - actual formula is generated by release.yml workflow
# and pushed to wickes1/homebrew-tap

cask "komet" do
  version "0.0.0"
  sha256 "GENERATED_BY_RELEASE_WORKFLOW"

  url "https://github.com/wickes1/Komet/releases/download/v#{version}/Komet.dmg"
  name "Komet"
  desc "Minimal, lightning-fast application launcher for macOS"
  homepage "https://github.com/wickes1/Komet"

  app "Komet.app"
end
